[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sk-payment-orchestrator"
version = "0.1.0"
description = "payment-orchestrator for SahulatKar"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn[standard]>=0.29.0",
    "sk-shared"
]
