import hashlib
import uuid
from datetime import datetime, timedelta, timezone

from fastapi import HTTPException, status
from reportlab.pdfgen import canvas
from sqlalchemy import select
from sqlalchemy.orm import joinedload
from sqlalchemy.ext.asyncio import AsyncSession

from sk_shared.constants import OrderState
from sk_shared.models.contracts import MurabahaContract, WakalahAgreement
from sk_shared.models.order import Order
from sk_shared.models.product import Product
from sk_shared.storage import get_storage_client
from src.config import settings
from src.core.kms import KMSProvider
from src.core.logging import logger
from src.schemas.contracts import MurabahaGenerateRequest, WakalahGenerateRequest
from .contract_signer import ContractSignerService


class ContractGeneratorService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.storage = get_storage_client(settings)

    def _build_pdf(self, title: str, lines: list[str], clauses: list[str] = None) -> bytes:
        import io
        buffer = io.BytesIO()
        c = canvas.Canvas(buffer)
        c.setTitle(title)
        
        # Header
        c.setFont("Helvetica-Bold", 16)
        c.drawCentredString(300, 800, "SahulatKar (Pvt) Ltd.")
        c.setFont("Helvetica", 10)
        license_label = (
            f"SECP License: {settings.SECP_LICENSE_NUMBER}"
            if settings.SECP_LICENSE_NUMBER
            else "SECP Licensed Entity"
        )
        c.drawCentredString(300, 785, f"{license_label} | Shariah Compliant BNPL Platform")
        c.line(50, 775, 550, 775)

        # Title
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, 750, title)
        c.setFont("Helvetica", 10)

        y = 720
        # Metadata Lines
        for line in lines:
            if y < 100:
                c.showPage()
                y = 800
            c.drawString(50, y, line)
            y -= 15

        # Clauses
        if clauses:
            y -= 20
            c.setFont("Helvetica-Bold", 11)
            c.drawString(50, y, "TERMS AND CONDITIONS:")
            c.setFont("Helvetica", 9)
            y -= 15
            for clause in clauses:
                if y < 100:
                    c.showPage()
                    y = 800
                # Basic wrapping for long clauses
                words = clause.split()
                line = ""
                for word in words:
                    if len(line + word) > 100:
                        c.drawString(50, y, line)
                        y -= 12
                        line = word + " "
                    else:
                        line += word + " "
                c.drawString(50, y, line)
                y -= 15

        # Footer
        c.setFont("Helvetica-Oblique", 8)
        c.drawString(50, 50, "Generated by SahulatKar Digital Signature System (ETO 2002 Compliant)")
        c.drawRightString(550, 50, "Page 1 | Integrity Hash: Verification Required")

        c.save()
        return buffer.getvalue()

    async def _persist_pdf(self, contract_number: str, payload: bytes) -> str:
        # SEC-03 FIX: Use UUID prefix to prevent predictable URL enumeration
        file_key = f"contracts/{uuid.uuid4()}/{contract_number}.pdf"
        if not settings.S3_BUCKET and settings.ENVIRONMENT != "production":
            logger.warning("CONTRACT_STORAGE_LOCAL_FALLBACK: using local storage for contract PDFs")
        return await self.storage.upload(file_key, payload)

    @staticmethod
    def _contract_number(prefix: str) -> str:
        return f"SAK-{prefix}-{datetime.now().year}-{uuid.uuid4().hex[:8].upper()}"

    async def generate_wakalah(self, user_id: int, req: WakalahGenerateRequest, redis) -> WakalahAgreement:
        # Load order with related product and kyc
        order = await self.db.scalar(
            select(Order).where(Order.id == req.order_id, Order.user_id == user_id, Order.deleted_at.is_(None))
        )
        if order is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ORDER_NOT_FOUND")

        from sk_shared.models.kyc import CustomerProfile
        from sk_shared.models.auth import User

        profile = await self.db.scalar(select(CustomerProfile).where(CustomerProfile.user_id == user_id))
        user_rec = await self.db.scalar(select(User).where(User.id == user_id))

        if not user_rec:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="USER_NOT_FOUND")

        # Build principal info — CustomerProfile preferred but not mandatory.
        # The KYC gate (user.status == 'active') is enforced at order initiation.
        if profile:
            first = getattr(profile, "first_name", "") or ""
            last = getattr(profile, "last_name", "") or ""
            principal_name = f"{first} {last}".strip() or "Customer"
            # CNIC may be AES-encrypted bytes; decrypt safely
            raw_cnic = getattr(profile, "cnic", None)
            if raw_cnic and isinstance(raw_cnic, (bytes, bytearray)):
                try:
                    principal_cnic = KMSProvider().decrypt(raw_cnic)
                except Exception:
                    principal_cnic = ""
            else:
                principal_cnic = str(raw_cnic) if raw_cnic else ""
        else:
            first = getattr(user_rec, "first_name", "") or ""
            last = getattr(user_rec, "last_name", "") or ""
            principal_name = f"{first} {last}".strip() or "Customer"
            principal_cnic = ""

        principal_info = {
            "name": principal_name,
            "cnic": principal_cnic,
            "phone": user_rec.phone,
        }

        existing = await self.db.scalar(
            select(WakalahAgreement).where(
                WakalahAgreement.order_id == order.id,
                WakalahAgreement.user_id == user_id,
                WakalahAgreement.deleted_at.is_(None),
            )
        )
        if existing is not None:
            existing._dev_otp = await ContractSignerService.issue_signing_otp(self.db, redis, "wakalah", existing.id, user_id)
            return existing

        product = await self.db.scalar(
            select(Product).options(joinedload(Product.merchant)).where(Product.id == order.product_id)
        ) if order.product_id else None
        
        order.status = OrderState.CONTRACTS_PENDING
        contract_number = self._contract_number("WAK")
        lines = [
            f"Contract Number: {contract_number}",
            f"Principal: {principal_info['name']} (CNIC: {principal_info['cnic']})",
            (
                f"Agent: {settings.COMPANY_LEGAL_NAME} (License: {settings.SECP_LICENSE_NUMBER})"
                if settings.SECP_LICENSE_NUMBER
                else f"Agent: {settings.COMPANY_LEGAL_NAME}"
            ),
            f"Merchant: {product.merchant.name if product and product.merchant else 'Direct Merchant'}",
            f"Authorized Amount: PKR {order.total_amount:,.2f}",
            "Price Variance Tolerance: 5.00%",
            f"Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        ]
        clauses = [
            "1. APPOINTMENT: The Principal hereby appoints SahulatKar as their Agent (Wakeel) to purchase the specified product on their behalf.",
            "2. AUTHORIZATION: The Agent is authorized to pay up to the Authorized Amount plus Variance for the product.",
            "3. AGENCY FEE: The agency fee for this service is included in the Murabaha markup explicitly disclosed in the subsequent contract.",
            "4. VALIDITY: This agency authorization is valid for 24 hours from the time of digital signing.",
            "5. LEGAL BASIS: This agreement is electronically signed under the Electronic Transactions Ordinance 2002."
        ]
        
        pdf = self._build_pdf("Wakalah Agreement (Agency)", lines, clauses)
        pdf_hash = hashlib.sha256(pdf).hexdigest()
        pdf_path = await self._persist_pdf(contract_number, pdf)

        kms = KMSProvider()
        # SEC-10: Store principal_name at-rest encrypted alongside CNIC
        try:
            encrypted_name = kms.encrypt(principal_info["name"]) if principal_info["name"] else None
        except Exception:
            encrypted_name = None

        contract = WakalahAgreement(
            order_id=order.id,
            user_id=user_id,
            contract_number=contract_number,
            authorized_amount=order.total_amount,
            contract_pdf_path=pdf_path,
            contract_hash=pdf_hash,
            otp_reference=str(uuid.uuid4()),
            principal_name=principal_info["name"],
            principal_name_encrypted=encrypted_name,
            agent_name=settings.COMPANY_LEGAL_NAME,
            principal_cnic=kms.encrypt(principal_info["cnic"]),
            principal_phone=principal_info["phone"],
            product_description=product.name if product else "Product",
            merchant_name=product.merchant.name if product and product.merchant else "Merchant",
            product_url=product.url if product else None,
            valid_until=datetime.now(timezone.utc) + timedelta(hours=24)
        )
        self.db.add(contract)
        await self.db.commit()
        await self.db.refresh(contract)

        contract._dev_otp = await ContractSignerService.issue_signing_otp(self.db, redis, "wakalah", contract.id, user_id)
        return contract

    async def generate_murabaha(self, user_id: int, req: MurabahaGenerateRequest, redis) -> MurabahaContract:
        order = await self.db.scalar(
            select(Order).where(Order.id == req.order_id, Order.user_id == user_id, Order.deleted_at.is_(None))
        )
        if order is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ORDER_NOT_FOUND")

        wakalah = await self.db.scalar(
            select(WakalahAgreement).where(
                WakalahAgreement.order_id == order.id,
                WakalahAgreement.user_id == user_id,
                WakalahAgreement.deleted_at.is_(None),
            )
        )
        if wakalah is None or wakalah.signed_at is None:
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="WAKALAH_NOT_SIGNED")
        
        # BUG-06 FIX: Check if Wakalah has expired (24-hour validity window)
        if wakalah.valid_until:
            valid_until = wakalah.valid_until if wakalah.valid_until.tzinfo else wakalah.valid_until.replace(tzinfo=timezone.utc)
            if datetime.now(timezone.utc) > valid_until:
                raise HTTPException(status_code=status.HTTP_410_GONE, detail="WAKALAH_EXPIRED")

        existing = await self.db.scalar(
            select(MurabahaContract).where(
                MurabahaContract.order_id == order.id,
                MurabahaContract.user_id == user_id,
                MurabahaContract.deleted_at.is_(None),
            )
        )
        if existing is not None:
            existing._dev_otp = await ContractSignerService.issue_signing_otp(self.db, redis, "murabaha", existing.id, user_id)
            return existing

        product = await self.db.scalar(
            select(Product).options(joinedload(Product.merchant)).where(Product.id == order.product_id)
        ) if order.product_id else None
        cost_price = float(product.cost_price if product else order.total_amount)

        profit_map = {3: 2.5, 4: 4.0, 6: 7.0, 12: 15.0}
        profit_rate_pct = float(profit_map.get(req.installment_count, 4.0))
        profit_amount = round(cost_price * (profit_rate_pct / 100), 2)
        total_sale_price = round(cost_price + profit_amount, 2)

        contract_number = self._contract_number("MUR")
        lines = [
            f"Contract Number: {contract_number}",
            f"Cost Price: PKR {cost_price:,.2f} (Shariah Disclosure: MANDATORY)",
            f"Profit Amount: PKR {profit_amount:,.2f} ({profit_rate_pct}% markup)",
            f"Total Sale Price: PKR {total_sale_price:,.2f}",
            f"Installment Plan: {req.installment_count} Months",
            f"Down Payment: PKR {float(order.down_payment_amount or 0):,.2f}",
        ]
        clauses = [
            "1. MURABAHA SALE: The Seller (SahulatKar) sells and the Buyer (Customer) buys the goods at the Total Sale Price disclosed above.",
            "2. OWNERSHIP: Ownership and risk of the goods shall transfer to the Buyer upon physical delivery and confirmation.",
            "3. LATE PAYMENT CHARITY: In case of delay in payment of installments, the Buyer shall pay a late fee specified in the schedule. 100% of such collection shall be donated to Edhi Foundation. SahulatKar shall retain ZERO profit from late fees.",
            "4. TASDEEQ NOTICE: Defaults will be reported to TASDEEQ (Credit Bureau) in accordance with the laws of Pakistan.",
            "5. NO INTEREST: This is a cost-plus-profit sale (Murabaha). No interest (Riba) is charged on this transaction."
        ]

        pdf = self._build_pdf("Murabaha Contract (Cost-Plus Sale)", lines, clauses)
        pdf_hash = hashlib.sha256(pdf).hexdigest()
        pdf_path = await self._persist_pdf(contract_number, pdf)

        down_payment = float(order.down_payment_amount or 0)
        repayable_amount = round(total_sale_price - down_payment, 2)
        installment_amount = round(repayable_amount / req.installment_count, 2)
        schedule = [
            {"installment_no": n + 1, "amount": installment_amount, "status": "pending"}
            for n in range(req.installment_count)
        ]

        contract = MurabahaContract(
            order_id=order.id,
            user_id=user_id,
            wakalah_agreement_id=wakalah.id,
            contract_number=contract_number,
            cost_price=cost_price,
            profit_amount=profit_amount,
            profit_rate_pct=profit_rate_pct,
            total_sale_price=total_sale_price,
            installment_count=req.installment_count,
            installment_schedule=schedule,
            contract_pdf_path=pdf_path,
            contract_hash=pdf_hash,
            otp_reference=str(uuid.uuid4()),
            template_version="1.0",
            validated_by_shariah_board=True,
            valid_until=datetime.now(timezone.utc) + timedelta(days=settings.MURABAHA_VALIDITY_DAYS),
        )
        self.db.add(contract)
        await self.db.commit()
        await self.db.refresh(contract)

        contract._dev_otp = await ContractSignerService.issue_signing_otp(self.db, redis, "murabaha", contract.id, user_id)
        return contract
