apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgbouncer
  labels:
    app: pgbouncer
    component: infra
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: pgbouncer
