apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  labels:
    app: pgbouncer
    component: infra
spec:
  type: ClusterIP
  selector:
    app: pgbouncer
  ports:
    - name: pgbouncer
      port: 6432
      targetPort: pgbouncer
