apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

images:
  - name: sk-payment-orchestrator
    newName: sk-payment-orchestrator
    newTag: latest
