apiVersion: v1
kind: Service
metadata:
  name: credit-engine
  labels:
    app: credit-engine
    component: backend
spec:
  type: ClusterIP
  selector:
    app: credit-engine
  ports:
    - name: http
      port: 80
      targetPort: http
