apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - migration-job.yaml
  - serviceaccounts.yaml
  - network-policies
  - gateway
  - product-service
  - credit-engine
  - payment-orchestrator
  - ledger-service
  - notification-service
  - web-admin
  - web-customer
  - pgbouncer
