apiVersion: v1
kind: ServiceAccount
metadata:
  name: sk-migration
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sk-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sk-product-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sk-credit-engine
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sk-payment-orchestrator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sk-ledger-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sk-notification-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sk-web-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sk-web-customer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sk-pgbouncer
