"use client";

import { FileBarChart } from "lucide-react";
import { useEffect, useState } from "react";
import { DataTable } from "@/components/admin/data-table";
import { adminApi } from "@/lib/api-client";

interface ReportItem {
  id: number;
  report_type: string;
  period: string;
  generated_at: string;
  submitted_at: string | null;
  reference_number: string | null;
  generated_by_email: string | null;
}

interface ReportsSummary {
  by_type: { report_type: string; count: number; last_generated: string | null }[];
}

export default function ReportsPage() {
  const [reports, setReports] = useState<ReportItem[]>([]);
  const [total, setTotal] = useState(0);
  const [summary, setSummary] = useState<ReportsSummary | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      adminApi.get<{ items: ReportItem[]; pagination: { total: number } }>("/admin/reports?limit=100"),
      adminApi.get<ReportsSummary>("/admin/reports/summary"),
    ])
      .then(([r, s]) => {
        setReports(r.items);
        setTotal(r.pagination.total);
        setSummary(s);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const columns = [
    { key: "reference_number", label: "Reference", render: (v: unknown) => <span className="font-mono text-sm text-white">{v ? String(v) : "—"}</span> },
    { key: "report_type", label: "Type", render: (v: unknown) => <span className="text-slate-300">{String(v).replace(/_/g, " ").toUpperCase()}</span> },
    { key: "period", label: "Period", render: (v: unknown) => <span className="text-slate-400">{new Date(String(v)).toLocaleDateString()}</span> },
    { key: "generated_by_email", label: "Generated By", render: (v: unknown) => <span className="text-slate-400">{v ? String(v) : "—"}</span> },
    { key: "generated_at", label: "Generated At", render: (v: unknown) => <span className="text-slate-400">{new Date(String(v)).toLocaleString()}</span> },
    {
      key: "submitted_at",
      label: "Submitted",
      render: (v: unknown) => (
        <span className={v ? "text-emerald-400" : "text-amber-400"}>{v ? new Date(String(v)).toLocaleDateString() : "Pending"}</span>
      ),
    },
  ];

  return (
    <section className="space-y-6">
      <div>
        <p className="text-xs uppercase tracking-[0.3em] text-slate-400">AD-34</p>
        <h2 className="mt-2 text-2xl font-semibold text-white">Reporting engine</h2>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        {(summary?.by_type ?? []).map((t) => (
          <div key={t.report_type} className="glass-panel rounded-xl p-4">
            <div className="flex items-center gap-2 text-sm text-slate-400">
              <FileBarChart className="h-4 w-4 text-blue-500" />
              {t.report_type.replace(/_/g, " ").toUpperCase()}
            </div>
            <p className="mt-2 text-2xl font-bold text-white">{t.count}</p>
            <p className="text-xs text-slate-500">
              {t.last_generated ? `Last: ${new Date(t.last_generated).toLocaleDateString()}` : "Never generated"}
            </p>
          </div>
        ))}
        {(!summary || summary.by_type.length === 0) && !loading && (
          <div className="glass-panel rounded-xl p-4 sm:col-span-2 xl:col-span-3">
            <p className="text-sm text-slate-500">No reports generated yet.</p>
          </div>
        )}
      </div>

      <section className="glass-panel rounded-[2rem] p-5">
        <h3 className="text-lg font-semibold text-white">Generated &amp; scheduled reports</h3>
        <p className="mt-1 text-sm text-slate-400">
          Regulatory filings generated from Finance, Compliance, and Analytics modules.
        </p>
        <div className="mt-4">
          <DataTable columns={columns} data={reports} keyField="id" loading={loading} />
        </div>
        <p className="mt-3 text-sm text-slate-400">
          Showing <span className="font-semibold text-white">{reports.length}</span> of{" "}
          <span className="font-semibold text-white">{total}</span> reports
        </p>
      </section>
    </section>
  );
}
