apiVersion: v1
kind: Service
metadata:
  name: web-admin
  labels:
    app: web-admin
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: web-admin
  ports:
    - name: http
      port: 80
      targetPort: http
