apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-default-deny.yaml
  - 01-allow-dns-egress.yaml
  - 10-gateway.yaml
  - 11-product-service.yaml
  - 12-credit-engine.yaml
  - 13-payment-orchestrator.yaml
  - 14-ledger-service.yaml
  - 15-notification-service.yaml
  - 16-web-admin.yaml
  - 17-web-customer.yaml
  - 18-pgbouncer.yaml
  - 19-migration-job.yaml
