from unittest.mock import AsyncMock

import pytest
from httpx import AsyncClient
from sk_shared.redis_client import RedisClient

from src.config import settings
from src.core.http_client import InternalServiceClient

pytestmark = pytest.mark.asyncio

async def test_registration_flow_success(client: AsyncClient, redis_mock: RedisClient):
    # Step 1: Initiate
    init_res = await client.post("/api/v1/auth/register/initiate", json={
        "phone": "+923001234567",
        "first_name": "Test",
        "last_name": "User"
    })
    assert init_res.status_code == 200
    data = init_res.json()
    assert "otp_token" in data
    assert "******" in data["masked_phone"]
    # Non-production environments are allowed to surface the OTP for local testing.
    assert data["dev_otp"] is not None
    assert len(data["dev_otp"]) == 6


async def test_registration_initiate_dispatches_otp_via_notification_service(client: AsyncClient, redis_mock: RedisClient, monkeypatch):
    """P1-10: registration OTPs must actually be dispatched for delivery, not
    just logged/returned as dev_otp — previously nothing called
    notification-service at all here, so no real user ever received a
    registration code by SMS.
    """
    mock_send = AsyncMock(return_value=True)
    monkeypatch.setattr(InternalServiceClient, "send_otp", mock_send)
    monkeypatch.setattr(settings, "NOTIFICATION_SMS_ENABLED", True)

    res = await client.post("/api/v1/auth/register/initiate", json={
        "phone": "+923001111222",
        "first_name": "Dispatch",
        "last_name": "Test",
    })
    assert res.status_code == 200

    mock_send.assert_awaited_once()
    call_kwargs = mock_send.await_args.kwargs
    assert call_kwargs["phone"] == "+923001111222"
    assert call_kwargs["purpose"] == "registration"
    assert len(call_kwargs["otp_code"]) == 6


async def test_registration_initiate_does_not_leak_otp_in_production(client: AsyncClient, redis_mock: RedisClient):
    orig_env = settings.ENVIRONMENT
    settings.ENVIRONMENT = "production"
    try:
        init_res = await client.post("/api/v1/auth/register/initiate", json={
            "phone": "+923009999999",
            "first_name": "Prod",
            "last_name": "User"
        })
    finally:
        settings.ENVIRONMENT = orig_env

    assert init_res.status_code == 200
    data = init_res.json()
    assert "otp_token" in data
    assert data.get("dev_otp") is None
    
    otp_token = data["otp_token"]
    
    # The pure 'OTP' generated by generate_otp is what goes into the hash,
    # however our fake redis holds the hashed value. In a real scenario we'd 
    # either intercept the sent SMS or we can't test without knowing it. 
    # Let's mock generate_otp or directly set the hash in redis.
    
    # Since we can't easily fetch the random OTP, let's verify invalid OTP logic first
    verify_res_invalid = await client.post("/api/v1/auth/verify-otp", json={
        "otp_token": otp_token,
        "otp_code": "000000"
    })
    assert verify_res_invalid.status_code == 400
    assert verify_res_invalid.json()["detail"] == "INVALID_OTP"

async def test_initiate_duplicate_phone(client: AsyncClient, db_setup):
    from sk_shared.models.auth import User
    import uuid
    # Let's seed a user directly using TestingSessionLocal inside the test or fixture
    from tests.conftest import TestingSessionLocal
    async with TestingSessionLocal() as session:
        user = User(uuid=uuid.uuid4(), phone="+923001111111", status="active")
        session.add(user)
        await session.commit()
        
    init_res = await client.post("/api/v1/auth/register/initiate", json={
        "phone": "+923001111111",
        "first_name": "Duplicate",
        "last_name": "User"
    })
    
    assert init_res.status_code == 409
    assert init_res.json()["detail"] == "PHONE_ALREADY_REGISTERED"


async def test_refresh_endpoint_rate_limit_returns_429_after_10(client: AsyncClient, redis_mock: RedisClient):
    """
    /auth/refresh must share the same rate_limit_auth dependency (10 req/min per IP)
    as its sibling auth endpoints (login, register/initiate, forgot-password, etc.).
    The refresh_token itself is bogus here — we only care that the 11th request is
    rejected by the rate limiter before it ever reaches AuthService.refresh_token.
    """
    for _ in range(10):
        resp = await client.post(
            "/api/v1/auth/refresh",
            json={"refresh_token": "not-a-real-token"},
        )
        assert resp.status_code == 401

    r = await client.post(
        "/api/v1/auth/refresh",
        json={"refresh_token": "not-a-real-token"},
    )
    assert r.status_code == 429
