apiVersion: v1
kind: Service
metadata:
  name: ledger-service
  labels:
    app: ledger-service
    component: backend
spec:
  type: ClusterIP
  selector:
    app: ledger-service
  ports:
    - name: http
      port: 80
      targetPort: http
